language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python3 src/main.py &
  - echo $! > pid
  - sleep 3
  - python3 test-runner.py
services:
  - mysql
before_script:
  - mysql -e 'create database ci;'
  - mysql -e 'CREATE USER "ci"@"localhost" IDENTIFIED BY "ci";'
  - mysql -e 'GRANT ALL PRIVILEGES ON * . * TO "ci"@"localhost";'
  - mysql -e 'FLUSH PRIVILEGES;'
